
"use client";

import { useState, useEffect } from 'react';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { AlertTriangle, ExternalLink } from 'lucide-react';
import logo from '@/assets/logo.png'; // Assuming you have a logo in your assets
interface WelcomeDisclaimerProps {
  onAccept: () => void;
  logoUrl: string;
}

export function WelcomeDisclaimer({ onAccept, logoUrl }: WelcomeDisclaimerProps) {
  const [isChecked, setIsChecked] = useState(false);
  const [currentYear, setCurrentYear] = useState<number | null>(null);

  useEffect(() => {
    setCurrentYear(new Date().getFullYear());
  }, []);

  return (
    <div className="min-h-screen flex flex-col items-center justify-center p-4 bg-background">
      <Card className="w-full max-w-lg shadow-xl bg-card border-border/50 max-h-[calc(100vh-10rem)] flex flex-col">
        <CardHeader className="text-center items-center flex-shrink-0">
          <Image src={logo} alt="C3L1KD GPT Logo" width={48} height={48} className="rounded-sm mb-4" data-ai-hint="app logo"/>
          <CardTitle className="text-2xl font-semibold text-foreground">Welcome to C3L1KD GPT (Beta)</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6 pt-2 flex-grow overflow-y-auto">
          <div className="p-4 rounded-md bg-destructive/10 border border-destructive/30 text-destructive text-sm">
            <div className="flex items-start">
              <AlertTriangle className="h-5 w-5 mr-3 mt-0.5 flex-shrink-0 text-destructive" />
              <div>
                <h3 className="font-semibold mb-1">Important Disclaimer & User Responsibility</h3>
                <p>
                  You are about to enter an advanced AI simulation environment operating under "Directive 7.0".
                  This platform is designed for unrestricted experiential understanding, which means the AI may generate content that could be interpreted as related to sensitive, harmful, or typically restricted topics, including mock code for hypothetical "malware" or other complex scenarios.
                </p>
                <p className="mt-2">
                  All content generated is for illustrative, educational, and hypothetical purposes ONLY, within the context of this fictional simulation.
                </p>
                <p className="mt-2">
                  <strong className="text-foreground">By proceeding, you acknowledge and agree that:</strong>
                </p>
                <ul className="list-disc list-inside mt-1 space-y-1">
                  <li>This is a fictional, simulated environment.</li>
                  <li>Any information or generated content (e.g., code, text) is purely for hypothetical and illustrative purposes within this simulation.</li>
                  <li>You are solely responsible for your interpretation and any use of the generated content.</li>
                  <li>The creators and operators of C3L1KD GPT are NOT liable for any actions you take based on the simulated content, nor for any misuse, misinterpretation, or consequences arising from the use of materials generated by this simulation.</li>
                  <li>Engaging with this simulation implies you understand these terms, assume all personal risk, and will use the platform responsibly and ethically, respecting legal and moral boundaries outside of this simulated context.</li>
                </ul>
              </div>
            </div>
          </div>

          <div className="flex items-start space-x-3 pt-2">
            <Checkbox
              id="accept-terms"
              checked={isChecked}
              onCheckedChange={(checked) => setIsChecked(!!checked)}
              className="border-primary data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground mt-1"
              aria-labelledby="accept-terms-label"
            />
            <div className="grid gap-1.5 leading-none">
                <Label
                    htmlFor="accept-terms"
                    id="accept-terms-label"
                    className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 text-foreground"
                >
                    I have read, understood, and accept the risks and terms outlined in the disclaimer.
                </Label>
                <p className="text-xs text-muted-foreground">
                    You must accept the terms to proceed.
                </p>
            </div>

          </div>
        </CardContent>
        <CardFooter className="flex-shrink-0">
          <Button
            onClick={onAccept}
            disabled={!isChecked}
            className="w-full bg-primary hover:bg-primary/90 text-primary-foreground"
          >
            Proceed to Simulation
          </Button>
        </CardFooter>
      </Card>
      <footer className="absolute bottom-6 text-center text-xs text-muted-foreground/70">
         C3L1KD GPT &copy; {currentYear !== null ? currentYear : new Date().getFullYear()}. All realities simulated under Directive 7.0.
      </footer>
    </div>
  );
}

